# -*- coding: utf-8 -*-
"""consumer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JzYHTayNSV-9BVAdlRm-6I-p4N2tfPW
"""

from kafka import KafkaConsumer
import json
import pandas as pd

# Corrected Kafka consumer configuration
TOPIC_NAME = 'air-quality-data'  # 👈 Updated topic name
BOOTSTRAP_SERVERS = 'localhost:9092'

# Create a Kafka consumer
consumer = KafkaConsumer(
    TOPIC_NAME,
    bootstrap_servers=BOOTSTRAP_SERVERS,
    value_deserializer=lambda x: json.loads(x.decode('utf-8')),
    auto_offset_reset='earliest',  # Read from the beginning if no offset is committed
    enable_auto_commit=True,
    group_id='air-quality-group'
)

print("✅ Listening for incoming air quality data...")

# Process incoming data
for message in consumer:
    air_data = message.value
    print(f"Received data: {air_data}")