# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyNIHUpSb7tTMccHHRwOEJo5SSod6yR1
"""

import streamlit as st
import pandas as pd
import plotly.express as px
# Page title
st.title("🌫️ Real-Time Air Quality Monitoring Dashboard")

# Sample air quality data
data = {
    "Timestamp": ["2025-03-25 18:00", "2025-03-25 18:05", "2025-03-25 18:10"],
    "PM2.5": [15.01, 16.34, 18.56],
    "PM10": [18.56, 20.60, 22.78],
    "CO": [594.14, 634.19, 650.43],
    "NO2": [21.08, 22.28, 23.34],
    "O3": [97.28, 90.84, 88.23],
    "AQI": [2, 2, 3]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display data as table
st.write("### 📊 Raw Air Quality Data")
st.dataframe(df)

# Plot AQI over time
fig = px.line(df, x="Timestamp", y="AQI", title="Air Quality Index Over Time")
st.plotly_chart(fig)

# Plot PM2.5 and PM10 levels
fig_pm = px.line(df, x="Timestamp", y=["PM2.5", "PM10"], title="PM2.5 and PM10 Levels Over Time")
st.plotly_chart(fig_pm)

st.success("✅ Dashboard Updated Successfully!")